branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master

language: rust

jobs:
  include:
    # amd64 linux
    - rust: stable
      os: linux
      arch: amd64
    - rust: beta
      os: linux
      arch: amd64
    - rust: nightly
      env: FEATURES=--features=nightly
      os: linux
      arch: amd64

    # arm64 linux
    - rust: stable
      os: linux
      arch: arm64
    - rust: beta
      os: linux
      arch: arm64
    - rust: nightly
      env: FEATURES=--features=nightly
      os: linux
      arch: arm64

before_script:
  # cargo test for wasm and cargo check for android and osx targets doesn't
  # need to be repeated on other os and arch.
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_CPU_ARCH" = "amd64" ]; then
      rustup target add wasm32-wasi
      cargo install cargo-wasi
      curl -L https://github.com/CraneStation/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz | sudo tar xJf - --strip-components=1 -C /usr/local/bin wasmtime-dev-x86_64-linux/wasmtime

      rustup target add aarch64-linux-android
      rustup target add armv7-linux-androideabi

      rustup target add x86_64-apple-darwin
      rustup target add aarch64-apple-darwin
    fi

script:
  - cargo test --no-default-features
  - cargo test $FEATURES
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_CPU_ARCH" = "amd64" ]; then
      cargo check --target aarch64-linux-android
      cargo check --target armv7-linux-androideabi

      cargo check --target x86_64-apple-darwin
      cargo check --target aarch64-apple-darwin
    fi
