branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master
language: rust

jobs:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: FEATURES=--features=nightly
before_script:
  - rustup target add wasm32-wasi
  - cargo install cargo-wasi
  - curl -L https://github.com/CraneStation/wasmtime/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz | sudo tar xJf - --strip-components=1 -C /usr/local/bin wasmtime-dev-x86_64-linux/wasmtime
script:
  - cargo test --no-default-features
  - cargo test $FEATURES
  - cargo wasi test --no-default-features
  - cargo wasi test $FEATURES
