branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master

language: rust
os: linux
dist: focal

jobs:
  include:
    # amd64 linux
    - rust: stable
      arch: amd64
      before_install: 
      - sudo apt update
      - sudo apt install -y gcc-multilib # Allow compilation for 32-bit target
    - rust: beta
      arch: amd64
      before_install: 
      - sudo apt update
      - sudo apt install -y gcc-multilib
    - rust: nightly
      env: FEATURES=--features=nightly
      arch: amd64
      before_install: 
      - sudo apt update
      - sudo apt install -y gcc-multilib

    # arm64 linux
    - rust: stable
      arch: arm64
    - rust: beta
      arch: arm64
    - rust: nightly
      env: FEATURES=--features=nightly
      arch: arm64

install: ci/install.sh
script: ci/script.sh
